version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    environment:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    branches:
      only:
        - master
    steps:
      - checkout
      # - run: cd $CIRCLE_WORKING_DIRECTORY
      - run: cd docs/
      - run: bundle exec jekyll build
      - run: bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html